target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'shared', :path => '../shared'

  pod 'FirebaseAnalytics', '11.12.0'
  pod 'FirebaseCrashlytics', '11.12.0'
  pod 'FirebasePerformance', '11.12.0'
  pod 'FirebaseRemoteConfig', '11.12.0'
  pod 'FirebaseMessaging', '11.12.0'
end
